### PR TITLE
Parse reference datetime and timedelta from the same string

### LINKED ISSUE #104: parse_datetime fails to parse a string comprising both reference date and a time delta
Steps to reproduce: put this failing test case in the `#[cfg(test)]` module in `lib.rs` and then run `cargo test test_parse_datetime_reference_date_and_time_delta`:
```
        #[test]
        fn test_parse_datetime_reference_date_and_time_delta() {
            // $ TZ=UTC0 date -I -d "1996-02-29 +1 year"
            std::env::set_var("TZ", "UTC0");
            let actual = parse_datetime("1996-02-29 +1 year").expect("parse failed");

            // 1997-03-01
            let expected = chrono::NaiveDate::from_ymd_opt(1997, 3, 1)
                .unwrap()
                .and_hms_opt(0, 0, 0)
                .unwrap()
                .and_utc();
            assert_eq!(actual, expected);
        }
```

What happens now: the test fails because `parse_datetime()` returns an error.

What I expected to happen: the test passes, with date "1996-02-29" parsed as the reference date, "+1 year" as the additional time delta to add, and the returned date being "1997-03-01" (with placeholder time of 00:00:00 in timezone UTC).

### PR DESCRIPTION
**Pull request by jfinkels**
Change the `parse_datetime()` function so that it parses both a
reference date and a time delta from one string. The new implementation
attempts to parse the datetime from the longest possible prefix of the
string. The remainder of the string is parsed as the time delta. This
allows us to parse more combinations of reference dates and time deltas
more easily.

Fixes #104

### CODE REVIEW

**Comment by cakebaker** [comment]
Great to see you also fixed the failing `test_months` and `test_duration_parsing` in `parse_relative_time.rs` :)

File: src/parse_relative_time.rs [hunk 1]
```diff
@@ -278,6 +284,15 @@ mod tests {
         Ok(parsed - now)
     }
 
+    #[test]
+    fn test_empty_string() {
+        let now = Utc::now();
+        assert_eq!(
+            parse_relative_time_at_date(now, "").unwrap(),
+            now.checked_add_months(Months::new(0)).unwrap()
```
Comment (cakebaker) [inline src/parse_relative_time.rs:292]: Calling `checked_add_months` seems unnecessary and you can simplify it to just:
```suggestion
            now
```

File: src/lib.rs [hunk 2]
```diff
@@ -78,11 +78,67 @@ mod format {
...
+        (YYYYMMDDHHMMSS_T_SEP_HYPHENATED_OFFSET, 24),
+        (YYYYMMDDHHMMSS_HYPHENATED_OFFSET, 23),
+        (YYYYMMDDHHMMSS_T_SEP_HYPHENATED_OFFSET, 22),
+        (YYYYMMDDHHMM_HYPHENATED_OFFSET, 22),
+        (YYYYMMDDHHMM_UTC_OFFSET, 20),
+        (YYYYMMDDHHMM_OFFSET, 18),
+        (YYYYMMDDHHMM_ZULU_OFFSET, 18),
+    ];
+
+    pub(crate) const PATTERNS_NOTZ: [(&str, usize); 9] = [
```
Comment (cakebaker) [inline src/lib.rs:108]: I guess `NOTZ` is short for "no timezone"? If that's the case, wouldn't it be easier to read as `NO_TZ`?

File: src/lib.rs [hunk 3]
```diff
@@ -78,11 +78,67 @@ mod format {
...
+        (YYYYMMDDHHMMSS_HYPHENATED_ZULU, 20),
+        (YYYYMMDDHHMMSS_T_SEP_HYPHENATED_ZULU, 20),
+        (YYYYMMDDHHMMS_T_SEP, 19),
+        (YYYYMMDDHHMMS, 19),
+        (YYYY_MM_DD_HH_MM, 16),
+        (YYYYMMDDHHMM_DOT_SS, 15),
+        (YYYYMMDDHHMM, 12),
+    ];
+
+    pub(crate) const PATTERNS_DATE_NOTZ: [(&str, usize); 8] = [
```
Comment (cakebaker) [inline src/lib.rs:120]: See my previous comment.

File: src/parse_relative_time.rs (hunk 1 above)
Comment (jfinkels) [reply src/parse_relative_time.rs:292]: I think without this there was a type mismatch related to chrono's `DateTime<Local>` vs `DateTime<FixedOffset>` or something like that. I'll see if there's another way around this.

Comment (jfinkels) [reply src/parse_relative_time.rs:292]: (The same pattern appears in a few other places below, as well.)

Comment (jfinkels) [reply src/parse_relative_time.rs:292]: Nevermind, I was misremembering. Your suggestion works, I'll update it.

**Comment by jfinkels** [comment]
Sorry, I don't know how to interpret the "Basic CI / Run the fuzzers" job failure. Let me know if I should do anything about that.

**Comment by jfinkels** [comment]
I'll extract some of these changes into smaller pull requests.

**Comment by jfinkels** [comment]
Thanks for your patience. We've now merged quite a few smaller pull requests comprising changes extracted from this branch. I've now rebased on `main` and the smaller changeset should be easier to review now.

File: src/lib.rs [hunk 4]
```diff
@@ -88,7 +89,7 @@ mod format {
 
     /// Whether the pattern ends in the character `Z`.
     pub(crate) fn is_zulu(pattern: &str) -> bool {
-        pattern == YYYYMMDDHHMMSS_HYPHENATED_ZULU
+        pattern == YYYYMMDDHHMMSS_HYPHENATED_ZULU || pattern == YYYYMMDDHHMMSS_T_SEP_HYPHENATED_ZULU
```
Comment (cakebaker) [inline src/lib.rs:92]: To match the comment you can simplify it to:
```suggestion
        pattern.ends_with('Z')
```

**Comment by cakebaker** [comment]
Thanks for splitting it into multiple PRs, much appreciated :)
